services:
  library-development:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        PHP_VERSION: ${PHP_VERSION:-not-set}
    volumes:
      - {{PLACEHOLDER_DIR}}:/app
    command: ["composer", "php-library-test-docker-cmd"]
